home/genesis/Desktop/DNAModeling/venv/bin/python /home/genesis/Desktop/DNAModeling/controller.py 
Output saved to An error occurred in thread 20: /home/genesis/Desktop/DNAModeling/direction_functions.py:58: RuntimeWarning: invalid value encountered in sqrt
  return 2 * np.arcsin(np.sqrt((np.sin(np.abs(a[1] - b[1]) / 2)) ** 2 + np.cos(a[1]) * np.cos(b[1]) * (np.sin(np.abs(a[0] - b[0]) / 2)) ** 2))
Traceback (most recent call last):
  File "/home/genesis/Desktop/DNAModeling/./concatemerization/concatemerization_random.py", line 42, in <module>
    temp, length = direction_functions.get_propelled_directions(num_dir, last, deg)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/genesis/Desktop/DNAModeling/direction_functions.py", line 38, in get_propelled_directions
    assert (last[1] / np.cos(phi)) >= -1, f"got as last1: {last[1]} got as cos: {np.cos(phi)} got as phi: {phi} division: {last[1] / np.cos(phi)}"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: got as last1: -1.64396775207435e-16 got as cos: 6.123233995736766e-17 got as phi: -1.5707963267948966 division: -2.684803084806075

Output saved to An error occurred in thread 25: /home/genesis/Desktop/DNAModeling/direction_functions.py:58: RuntimeWarning: invalid value encountered in sqrt
  return 2 * np.arcsin(np.sqrt((np.sin(np.abs(a[1] - b[1]) / 2)) ** 2 + np.cos(a[1]) * np.cos(b[1]) * (np.sin(np.abs(a[0] - b[0]) / 2)) ** 2))
Traceback (most recent call last):
  File "/home/genesis/Desktop/DNAModeling/./concatemerization/concatemerization_random.py", line 42, in <module>
    temp, length = direction_functions.get_propelled_directions(num_dir, last, deg)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/genesis/Desktop/DNAModeling/direction_functions.py", line 38, in get_propelled_directions
    assert (last[1] / np.cos(phi)) >= -1, f"got as last1: {last[1]} got as cos: {np.cos(phi)} got as phi: {phi} division: {last[1] / np.cos(phi)}"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: got as last1: -1.105516262672919e-16 got as cos: 6.123233995736766e-17 got as phi: -1.5707963267948966 division: -1.8054450694561444

